name: Push checks

on:
  push:
    branches:
      - main
      - loki-stack

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER_NAME: cluster-demo
  GKE_REGION: europe-west1

jobs:
  deploy-loki:
    name: Deploy
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_REGION }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      - uses: azure/setup-helm@v1
        with:
          version: '3.7.2'
      - name: Deploy
        run: |
          set -x
          helm repo add kube-ops https://charts.kube-ops.io
          helm repo update
          if helm upgrade loki-stack ./helm_values/loki-stack.yaml --install --namespace hackathon-monitoring --values ./helm_values/loki-stack.yaml --wait --timeout 1m; then
            echo "deployment succeeded!"
          else
            echo "DEPLOYMENT FAILED! TRYING TO ROLLBACK"
            helm rollback loki-stack --namespace hackathon-monitoring
            exit 1
          fi