
name: Deploy at (with Terraform)

on:
  push:
    branches:
      - uat

env:
  GKE_CLUSTER_NAME: cluster-at
  GKE_REGION: europe-west1
  GKE_ENV: at

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_REGION }}
      - uses: azure/setup-helm@v1
        with:
          version: '3.7.2'
      - name: Deploy
        run: |
          cd terraform/
          terraform init
          terraform workspace select $GKE_ENV
          terraform workspace list
          terraform apply -auto-approve -var-file=environments/$GKE_ENV.tfvars
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}

